### ISSUE TITLE
Cilium etcd operator not able to create deployment.apps on Openshift

### ISSUE THREAD

**Issue by HoogWater** [cilium/cilium-etcd-operator#72] opened 2021-01-14 07:12 UTC
Hi,

when trying to deploy cilium with managed etcd on Openshift(OCP4.6) the cilium etcd operator is not able to create a etcd-operator deployment with the following error

`"unable to create etcd-operator deployment: deployments.apps \"etcd-operator\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"`

I am unable to find the cause at this point in time, any help is appreciated

**Comment by aanm** [comment] 2021-01-30 18:02
@HoogWater hello, this should be fixed since Cilium >= 1.8.5

**Comment by HoogWater** [comment] 2021-01-30 18:52
I tried with 1.9.0 and 1.9.1, same result. I'll try again with latest release

**Comment by aanm** [comment] 2021-01-31 10:53
@HoogWater if it still happens please open a GitHub issue in https://github.com/cilium/cilium and mention my GitHub username.

**Comment by pzhangch** [comment] 2021-11-25 20:10
@HoogWater i also encounter this issue, could you tell me if it works in your environment now? thanks

**Comment by pchaigno** [comment] 2021-11-29 18:35
Closing as we haven't heard back from the original author. Please open an issue on cilium/cilium if you hit this again, with reproduction steps and a sysdump.

**Closed as completed** 2021-11-29 18:38 UTC
